# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-06 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Dept', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Facultad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='objetoA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=30)),
                ('institucion', models.CharField(max_length=15)),
                ('fechaCreacion', models.DateField(default='2018-01-30')),
                ('fechaIngreso', models.DateField()),
                ('palabras_clave', models.CharField(max_length=30, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_tema', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='objetoa',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objeto.tema'),
        ),
    ]
