# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-13 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objeto', '0002_auto_20180212_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='archivoCatalogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archIndex', models.FileField(upload_to='archCat')),
                ('archElp', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='objetoa',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='objetoa',
            name='institucion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='objetoa',
            name='palabras_clave',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
