# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-18 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objeto', '0003_auto_20180212_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentariotxt', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='objetoa',
            name='sube',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='objeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objeto.objetoA'),
        ),
    ]
