# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-21 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objeto', '0005_auto_20180218_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetoa',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
