# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-06 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrousuario',
            options={'permissions': (('esEstudiante', 'Puede Descargar'), ('esProfesor', 'Puede Crear DEscargar Elminar y Modificar'))},
        ),
    ]
