# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-12 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20180212_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrousuario',
            name='tipo',
            field=models.CharField(blank=True, choices=[('e', 'estudiante'), ('p', 'profesor')], max_length=15, null=True),
        ),
    ]
