# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-30 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Dept', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Facultad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='objetoA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=30)),
                ('institucion', models.CharField(max_length=15)),
                ('fechaCreacion', models.DateField()),
                ('fechaIngreso', models.DateField()),
                ('palabras_clave', models.CharField(max_length=30)),
                ('archivo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PermisoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('e', 'estudiante'), ('p', 'profesor')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_tema', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=15)),
                ('clave', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('cedula', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repositorio.Departamento')),
                ('facultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repositorio.Facultad')),
            ],
        ),
        migrations.AddField(
            model_name='permisousuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repositorio.usuario'),
        ),
        migrations.AddField(
            model_name='objetoa',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repositorio.tema'),
        ),
    ]
