# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-06 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetoa',
            name='archivo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='objetoa',
            name='fechaCreacion',
            field=models.DateField(default='2018-01-30'),
        ),
    ]
