# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-06 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0002_auto_20180206_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetoa',
            name='archivo',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='objetoa',
            name='palabras_clave',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
