# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-06 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0003_auto_20180206_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetoa',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
